"""Add GDPR fields to User model

Revision ID: 1111eac261bd
Revises: 
Create Date: 2025-11-23 14:16:29.169074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1111eac261bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to allow existing rows
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('privacy_consent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('submission_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_submission_at', sa.DateTime(timezone=True), nullable=True))

    # Set default values for existing users
    op.execute("UPDATE users SET first_name = 'User' WHERE first_name IS NULL")
    op.execute("UPDATE users SET last_name = 'Unknown' WHERE last_name IS NULL")
    op.execute("UPDATE users SET language = 'en' WHERE language IS NULL")
    op.execute("UPDATE users SET privacy_consent = TRUE WHERE privacy_consent IS NULL")
    op.execute("UPDATE users SET submission_count = 1 WHERE submission_count IS NULL")

    # Now make required columns NOT NULL
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    op.alter_column('users', 'privacy_consent', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_submission_at')
    op.drop_column('users', 'submission_count')
    op.drop_column('users', 'privacy_consent')
    op.drop_column('users', 'language')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
